### ISSUE TITLE
Roatad labels

### ISSUE THREAD

**Issue by ganeshbabuhc** [pshivale/psd3#1]
Can u pls implement the same graph with rotated labels??
Like the graph below

[(http://bl.ocks.org/metmajer/5480307)]
![screenshot](https://cloud.githubusercontent.com/assets/14067832/13140566/dab12916-d658-11e5-9178-20d7031d635b.png)

**Comment by cviner** [comment]
I also think that this would be a very useful feature.

**Comment by pshivale** [comment]
I have added support for rotated labels.
Add the option to the config as rotateLabel: true
Please try the latest master branch.
I will create a release for this soon.

**Comment by pshivale** [comment]
Feature added in release 0.5
